/* ============================================================
 * data/species.js — ฐานข้อมูลพืช (Data Layer แยกจาก UI)
 * เพิ่มต้นไม้ใหม่ = เพิ่ม object ใน array นี้ (หรือย้ายไป API ภายหลัง)
 * ข้อมูลเป็นแนวทางทั่วไป ไม่รับประกันผล ขึ้นกับพันธุ์และสภาพแวดล้อม
 *
 * ฟิลด์เสริม (ไม่บังคับ ใช้ได้กับทุกชนิด):
 *   careNotes      ข้อความ "การดูแล" ที่แสดงใน Plant Detail
 *   warnings[]     คำเตือนสำคัญ แสดงเด่นใน Plant Detail
 *   extraChecks[]  งานตรวจเฉพาะชนิด {key,type,startDay,every,title('{name}'),description,steps}
 *   plantingSteps[] ขั้นตอนปลูกเฉพาะชนิด (แทนค่า default)
 *   doctorHints[]  กฎ Plant Doctor เฉพาะชนิด {symptoms[],when{qid:[values]},title,why,checks,actions}
 *   image.src      URL รูปจริงในอนาคต (null = ใช้ภาพวาด placeholder)
 * ============================================================ */
const PLANT_SPECIES = [
  {
    id: 'hibiscus', emoji: '🌺', nameTh: 'ชบา', nameEn: 'Hibiscus', scientificName: 'Hibiscus rosa-sinensis',
    category: 'ไม้พุ่มดอก', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 6, label: 'ชอบแดดจัด', text: 'ควรได้แดดอย่างน้อย 6 ชั่วโมงต่อวัน ยิ่งแดดดี ยิ่งออกดอกดก' },
    waterNeed: 'medium',
    wateringGuideline: 'ชอบดินชื้นแต่ไม่แฉะ ตรวจดินทุกเช้า ถ้าดินลึก 2–3 ซม. แห้ง ค่อยรดจนน้ำไหลออกก้นกระถาง',
    soilGuideline: 'ดินร่วนผสมปุ๋ยหมัก ระบายน้ำดี ถ้าปลูกกระถางใช้ดินผสมพร้อมปลูก',
    fertilizerGuideline: 'หลังตั้งตัวประมาณ 3 สัปดาห์ ใส่ปุ๋ยตามอัตราบนฉลาก ช่วงอยากให้ออกดอก ใช้สูตรที่ตัวกลางหรือตัวท้ายสูง (ตามคำแนะนำบนฉลาก)',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'ทนร้อนได้ดี ช่วงบ่ายร้อนจัดอาจเหี่ยวเล็กน้อย ถ้าฟื้นตอนเย็นถือว่าปกติ',
    floweringStartDay: 60,
    floweringNotes: 'ออกดอกได้เกือบทั้งปีเมื่อต้นแข็งแรง ดอกบานวันเดียวแล้วโรย เป็นเรื่องปกติ',
    pruningNotes: 'ตัดกิ่งแห้ง กิ่งยาวเกะกะ หลังดอกชุดใหญ่โรย จะช่วยให้แตกกิ่งใหม่และออกดอกเพิ่ม',
    pruneTasks: [{ day: 75, every: 30, title: 'ตัดแต่งกิ่งแห้งและกิ่งเกะกะ' }],
    pestNotes: 'เพลี้ยแป้ง (ปุยขาว) เพลี้ยอ่อน และไรแดง พบบ่อยช่วงอากาศแห้ง',
    diseaseNotes: 'ใบเหลืองร่วงมักเกิดจากน้ำขังหรือแดดไม่พอ',
    commonProblems: ['ใบเหลืองจากน้ำขัง', 'เพลี้ยแป้งตามยอดและใต้ใบ', 'ดอกร่วงตอนตูมเมื่อขาดน้ำ'],
    image: { kind: 'round5', petal: '#E8476A', center: '#F9D85E', bg: '#FDE3EA' },
    description: 'ไม้พุ่มดอกใหญ่ สีสด ปลูกง่าย เหมาะกับมือใหม่และอากาศร้อน',
  },
  {
    id: 'bougainvillea', emoji: '🌸', nameTh: 'เฟื่องฟ้า', nameEn: 'Bougainvillea', scientificName: 'Bougainvillea spp.',
    category: 'ไม้พุ่ม/ไม้เลื้อย', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 6, label: 'ชอบแดดจัดมาก', text: 'ยิ่งแดดจัดยิ่งออกดอกดี ถ้าแดดน้อยจะมีแต่ใบ' },
    waterNeed: 'low',
    wateringGuideline: 'ทนแล้ง ปล่อยให้ดินแห้งก่อนค่อยรด รดน้ำมากเกินไปจะได้ใบเยอะแต่ดอกน้อย',
    soilGuideline: 'ดินร่วนปนทราย ระบายน้ำดีมาก ห้ามน้ำขัง',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก ไม่ต้องใส่บ่อย ปุ๋ยไนโตรเจน (ตัวหน้า) สูงมากทำให้ใบเยอะดอกน้อย',
    fertStartDay: 30, fertIntervalDays: 45,
    temperatureNotes: 'ทนร้อนและแดดจัดได้ดีมาก เหมาะกับภาคกลาง',
    floweringStartDay: 75,
    floweringNotes: '"ดอก" สีสดที่เห็นคือใบประดับ ดอกจริงเป็นดอกเล็กสีขาวตรงกลาง มักออกดอกดีช่วงอากาศแห้ง',
    pruningNotes: 'ตัดแต่งหลังดอกชุดหนึ่งโรย จะแตกกิ่งใหม่และออกดอกชุดต่อไป ระวังหนาม ใส่ถุงมือ',
    pruneTasks: [{ day: 90, every: 45, title: 'ตัดแต่งกิ่งหลังดอกโรย (ใส่ถุงมือ ระวังหนาม)' }],
    pestNotes: 'หนอนกินใบ และเพลี้ยบางชนิด',
    diseaseNotes: 'ใบร่วงเมื่อย้ายที่หรือรดน้ำมากเกินไป',
    commonProblems: ['ใบเยอะไม่ออกดอก', 'ใบร่วงหลังย้ายกระถาง', 'หนอนกินใบ'],
    image: { kind: 'bract', petal: '#D6408F', center: '#FFF7E0', bg: '#FBE0EE' },
    description: 'ทนแล้ง ทนแดด สีสดทั้งปี เหมาะกับบ้านที่แดดจัด',
  },
  {
    id: 'portulaca', emoji: '🌼', nameTh: 'คุณนายตื่นสาย', nameEn: 'Moss rose', scientificName: 'Portulaca grandiflora',
    category: 'ไม้ล้มลุกดอก', difficulty: 'ง่ายมาก', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 6, label: 'ชอบแดดจัด', text: 'ต้องการแดดจัด ดอกจะบานตอนสายเมื่อแดดแรงและหุบช่วงบ่าย' },
    waterNeed: 'low',
    wateringGuideline: 'ใบอวบน้ำ เก็บน้ำได้ดี ไม่ต้องรดบ่อย รดเมื่อดินแห้ง',
    soilGuideline: 'ดินร่วนปนทราย ระบายน้ำดี กระถางตื้นก็ปลูกได้',
    fertilizerGuideline: 'ไม่ต้องการปุ๋ยมาก ใส่ปุ๋ยตามอัตราบนฉลากเป็นครั้งคราว',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'ชอบอากาศร้อน ทนแดดได้ดีมาก',
    floweringStartDay: 35,
    floweringNotes: 'ดอกบานวันเดียว แต่ออกดอกใหม่ต่อเนื่อง วันที่ฟ้าครึ้มดอกอาจไม่บาน',
    pruningNotes: 'ตัดยอดที่ยาวเกินไปเพื่อให้แตกพุ่ม ยอดที่ตัดนำไปปักชำได้ง่าย',
    pruneTasks: [],
    pestNotes: 'เพลี้ยอ่อน พบได้บ้าง',
    diseaseNotes: 'โคนเน่าถ้าดินแฉะนาน',
    commonProblems: ['โคนเน่าจากน้ำขัง', 'ดอกไม่บานเพราะแดดน้อย'],
    image: { kind: 'round5', petal: '#F7A21B', center: '#FFE36E', bg: '#FFF1D2', small: true },
    description: 'ปลูกง่ายมาก ทนแดด ทนแล้ง ปักชำต่อได้เรื่อย ๆ',
  },
  {
    id: 'periwinkle', emoji: '🌸', nameTh: 'แพงพวย', nameEn: 'Madagascar periwinkle', scientificName: 'Catharanthus roseus',
    category: 'ไม้ล้มลุกดอก', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 4, label: 'แดดจัดถึงแดดครึ่งวัน', text: 'แดดครึ่งวันขึ้นไปก็ออกดอกได้ แดดจัดจะดกกว่า' },
    waterNeed: 'low',
    wateringGuideline: 'ไม่ชอบน้ำขัง รดเมื่อดินแห้ง ช่วงหน้าฝนให้ระวังดินแฉะเป็นพิเศษ',
    soilGuideline: 'ดินร่วน ระบายน้ำดีมาก',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก เดือนละครั้งหลังตั้งตัว',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'ทนร้อน ไม่ชอบอากาศชื้นแฉะนาน ๆ',
    floweringStartDay: 45,
    floweringNotes: 'ออกดอกต่อเนื่องเกือบทั้งปี',
    pruningNotes: 'เด็ดยอดเมื่อต้นสูงราว 10–15 ซม. เพื่อให้แตกพุ่ม',
    pruneTasks: [{ day: 21, title: 'เด็ดยอดให้แตกพุ่ม' }],
    pestNotes: 'เพลี้ยอ่อน เพลี้ยแป้ง',
    diseaseNotes: 'รากเน่า โคนเน่า เมื่อดินแฉะนาน (พบบ่อยหน้าฝน)',
    commonProblems: ['ต้นเหี่ยวทั้งที่ดินชื้น (อาจรากเน่า)', 'ใบเหลืองช่วงฝนชุก'],
    image: { kind: 'round5', petal: '#F06BA8', center: '#B3245F', bg: '#FDE4F0', small: true },
    description: 'ดอกน่ารัก ออกดอกทั้งปี ขอแค่ดินไม่แฉะ',
  },
  {
    id: 'marigold', emoji: '🌼', nameTh: 'ดาวเรือง', nameEn: 'Marigold', scientificName: 'Tagetes erecta',
    category: 'ไม้ล้มลุกดอก', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 6, label: 'ชอบแดดจัด', text: 'ต้องการแดดอย่างน้อย 6 ชั่วโมง ถ้าแดดน้อยต้นจะยืดและดอกเล็ก' },
    waterNeed: 'medium',
    wateringGuideline: 'ชอบดินชื้นสม่ำเสมอ แต่ไม่แฉะ รดที่โคนต้น เลี่ยงรดโดนดอก',
    soilGuideline: 'ดินร่วนผสมปุ๋ยหมัก ระบายน้ำดี',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก ช่วงก่อนออกดอก ไม่ใส่ไนโตรเจนมากเกินไป',
    fertStartDay: 14, fertIntervalDays: 21,
    temperatureNotes: 'ปลูกได้ทั้งปี ช่วงอากาศเย็นดอกจะสวยเป็นพิเศษ',
    floweringStartDay: 45,
    floweringNotes: 'เป็นไม้ล้มลุก อายุประมาณ 3–4 เดือน หลังออกดอกเต็มที่ต้นจะค่อย ๆ โทรม เป็นเรื่องปกติ',
    pruningNotes: 'เด็ดยอดช่วงต้นอายุประมาณ 3 สัปดาห์ให้แตกกิ่ง และเด็ดดอกที่เหี่ยวออก',
    pruneTasks: [{ day: 21, title: 'เด็ดยอดให้แตกกิ่ง' }],
    deadhead: true,
    pestNotes: 'เพลี้ยไฟ หนอนเจาะดอก ไรแดง',
    diseaseNotes: 'โคนเน่าเมื่อน้ำขัง ใบจุดช่วงฝนชุก',
    commonProblems: ['หนอนเจาะดอก', 'เพลี้ยไฟทำให้ใบหงิก', 'ต้นล้มเพราะโคนเน่า'],
    image: { kind: 'pom', petal: '#F7A21B', center: '#E07B00', bg: '#FFF0CC' },
    description: 'ดอกสีเหลืองส้มสดใส โตเร็ว เห็นผลไว เหมาะเป็นต้นแรก',
  },
  {
    id: 'zinnia', emoji: '🌸', nameTh: 'บานชื่น', nameEn: 'Zinnia', scientificName: 'Zinnia elegans',
    category: 'ไม้ล้มลุกดอก', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 6, label: 'ชอบแดดจัด', text: 'ต้องการแดดจัด อากาศถ่ายเท' },
    waterNeed: 'medium',
    wateringGuideline: 'รดที่โคนต้น ไม่รดโดนใบ เพื่อลดโอกาสเกิดราแป้ง รดเมื่อดินแห้ง',
    soilGuideline: 'ดินร่วน ระบายน้ำดี',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก ไม่ต้องใส่มาก',
    fertStartDay: 14, fertIntervalDays: 21,
    temperatureNotes: 'ชอบอากาศร้อน ช่วงฝนชุกใบอาจเป็นราแป้ง',
    floweringStartDay: 50,
    floweringNotes: 'ไม้ล้มลุก ตัดดอกไปปักแจกันได้ ยิ่งตัดยิ่งออกดอกใหม่',
    pruningNotes: 'เด็ดยอดเมื่อมีใบ 3–4 คู่ และตัดดอกที่โรยออก',
    pruneTasks: [{ day: 25, title: 'เด็ดยอดให้แตกกิ่ง' }],
    deadhead: true,
    pestNotes: 'เพลี้ยอ่อน ไรแดง',
    diseaseNotes: 'ราแป้ง (ผงขาวบนใบ) เมื่ออากาศชื้นและลมไม่ถ่ายเท',
    commonProblems: ['ผงขาวบนใบ (ราแป้ง)', 'ใบล่างแห้ง'],
    image: { kind: 'daisy', petal: '#F25C8A', center: '#F7C948', bg: '#FDE2EB', layers: 2 },
    description: 'สีสันหลากหลาย ตัดดอกปักแจกันได้ โตไว',
  },
  {
    id: 'sunflower', emoji: '🌻', nameTh: 'ทานตะวัน', nameEn: 'Sunflower', scientificName: 'Helianthus annuus',
    category: 'ไม้ล้มลุกดอก', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 7, label: 'ชอบแดดจัดมาก', text: 'ต้องการแดดเต็มวัน 7 ชั่วโมงขึ้นไป' },
    waterNeed: 'medium',
    wateringGuideline: 'รดเมื่อดินแห้ง ช่วงตั้งดอกต้องการน้ำสม่ำเสมอ',
    soilGuideline: 'ดินร่วนลึก ระบายน้ำดี ถ้าปลูกกระถางเลือกพันธุ์แคระ และใช้กระถางใหญ่',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก ช่วงต้นเริ่มยืดตัว',
    fertStartDay: 20, fertIntervalDays: 21,
    temperatureNotes: 'ชอบอากาศร้อน ลมแรงอาจทำให้ต้นล้ม',
    floweringStartDay: 60,
    floweringNotes: 'พันธุ์ทั่วไปออกดอกต้นละ 1 ดอก แล้วจบรอบชีวิต ปลูกใหม่ได้เรื่อย ๆ',
    pruningNotes: 'ไม่ต้องตัดแต่ง ถ้าต้นสูงให้ปักหลักค้ำ',
    pruneTasks: [{ day: 35, title: 'ปักหลักค้ำต้น (ถ้าต้นสูงหรือเอียง)' }],
    pestNotes: 'หนอนกินใบ เพลี้ยอ่อน นกกินเมล็ด',
    diseaseNotes: 'โคนเน่าเมื่อน้ำขัง',
    commonProblems: ['ต้นล้มเพราะลม', 'หนอนกินใบ'],
    image: { kind: 'daisy', petal: '#F9C31E', center: '#6B3E1E', bg: '#FFF4C7', big: true },
    description: 'ดอกใหญ่ สดใส เห็นการเติบโตชัดเจน สนุกสำหรับมือใหม่',
  },
  {
    id: 'jasmine', emoji: '🤍', nameTh: 'มะลิ', nameEn: 'Arabian jasmine', scientificName: 'Jasminum sambac',
    category: 'ไม้พุ่มดอกหอม', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 5, label: 'ชอบแดดค่อนวัน', text: 'แดด 5–6 ชั่วโมงขึ้นไปออกดอกดี' },
    waterNeed: 'medium',
    wateringGuideline: 'ชอบดินชื้นสม่ำเสมอ ไม่แฉะ ช่วงหน้าร้อนตรวจดินทุกเช้า',
    soilGuideline: 'ดินร่วนผสมปุ๋ยหมัก ระบายน้ำดี',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก หลังตัดแต่งกิ่งเป็นช่วงที่ต้นต้องการอาหาร',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'ชอบอากาศร้อน ออกดอกดกช่วงหน้าร้อน',
    floweringStartDay: 75,
    floweringNotes: 'ดอกหอม ออกเป็นช่วง ๆ หลังตัดแต่งกิ่งจะออกดอกรุ่นใหม่',
    pruningNotes: 'ตัดแต่งกิ่งหลังดอกชุดหนึ่งหมด เพื่อให้แตกยอดใหม่ที่จะให้ดอก',
    pruneTasks: [{ day: 90, every: 45, title: 'ตัดแต่งกิ่งหลังดอกชุดหมด' }],
    pestNotes: 'หนอนเจาะดอก ไรแดง เพลี้ยแป้ง',
    diseaseNotes: 'ใบเหลืองจากน้ำขัง',
    commonProblems: ['หนอนเจาะดอกตูม', 'ใบมีจุดเหลืองซีดจากไรแดง'],
    image: { kind: 'star', petal: '#FFFFFF', center: '#F4E3A1', bg: '#E8F4EC', stroke: '#CFE3D6' },
    description: 'ดอกขาวหอม ปลูกง่าย ร้อยมาลัยได้',
  },
  {
    id: 'gardenia', emoji: '🤍', nameTh: 'พุด (พุดซ้อน)', nameEn: 'Gardenia', scientificName: 'Gardenia jasminoides',
    category: 'ไม้พุ่มดอกหอม', difficulty: 'ปานกลาง', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 4, label: 'แดดครึ่งวัน', text: 'แดดเช้าถึงครึ่งวันกำลังดี แดดบ่ายจัดมากอาจทำให้ใบไหม้' },
    waterNeed: 'medium',
    wateringGuideline: 'ชอบดินชื้นสม่ำเสมอ ไม่แฉะ ไม่ปล่อยให้แห้งสนิทนาน',
    soilGuideline: 'ดินร่วนผสมปุ๋ยหมักหรือใบไม้ผุ (ชอบดินเป็นกรดเล็กน้อย)',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก หากยอดอ่อนซีดเหลืองอาจต้องปรับดิน ลองปรึกษาร้านต้นไม้',
    fertStartDay: 30, fertIntervalDays: 30,
    temperatureNotes: 'ไม่ชอบแดดบ่ายร้อนจัดโดยตรง',
    floweringStartDay: 90,
    floweringNotes: 'ดอกขาวหอม ดอกตูมอาจร่วงถ้าขาดน้ำหรือย้ายที่บ่อย',
    pruningNotes: 'ตัดแต่งทรงเบา ๆ หลังดอกหมดชุด',
    pruneTasks: [{ day: 120, every: 60, title: 'ตัดแต่งทรงพุ่มเบา ๆ' }],
    pestNotes: 'เพลี้ยแป้ง เพลี้ยหอย ราดำตามมา',
    diseaseNotes: 'ยอดอ่อนเหลืองซีด (อาจเกี่ยวกับดินเป็นด่าง) ราดำ',
    commonProblems: ['ยอดอ่อนเหลืองซีด', 'ดอกตูมร่วง', 'คราบดำบนใบ (ราดำ)'],
    image: { kind: 'rose', petal: '#FFFDF6', center: '#F2E6B8', bg: '#EEF6E8', stroke: '#D9E6CF' },
    description: 'ดอกหอมสวย ต้องการความใส่ใจเรื่องดินและน้ำมากขึ้นเล็กน้อย',
  },
  {
    id: 'ixora', emoji: '🌺', nameTh: 'เข็ม', nameEn: 'Ixora', scientificName: 'Ixora spp.',
    category: 'ไม้พุ่มดอก', difficulty: 'ง่าย', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 5, label: 'แดดจัดถึงแดดครึ่งวัน', text: 'แดดครึ่งวันขึ้นไป ออกดอกเป็นช่อกลม' },
    waterNeed: 'medium',
    wateringGuideline: 'รดเมื่อดินเริ่มแห้ง ไม่ชอบน้ำขัง',
    soilGuideline: 'ดินร่วนผสมปุ๋ยหมัก (ชอบดินเป็นกรดเล็กน้อย)',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก ถ้าใบเหลืองแต่เส้นใบเขียว อาจเกี่ยวกับดิน ลองปรึกษาร้านต้นไม้',
    fertStartDay: 30, fertIntervalDays: 30,
    temperatureNotes: 'ทนร้อนได้ดี',
    floweringStartDay: 75,
    floweringNotes: 'ออกดอกเป็นช่อ ออกได้เกือบทั้งปี',
    pruningNotes: 'ตัดแต่งทรงพุ่มหลังดอกโรย จะแตกยอดใหม่และออกช่อใหม่',
    pruneTasks: [{ day: 90, every: 45, title: 'ตัดช่อดอกที่โรยและแต่งทรง' }],
    pestNotes: 'เพลี้ยอ่อน เพลี้ยแป้ง',
    diseaseNotes: 'ใบเหลืองซีดเมื่อดินไม่เหมาะ',
    commonProblems: ['ใบเหลืองแต่เส้นใบยังเขียว', 'เพลี้ยตามยอด'],
    image: { kind: 'cluster', petal: '#E8492F', center: '#F7C948', bg: '#FDE5DF' },
    description: 'ไม้พุ่มดอกช่อกลม ทนร้อน ตัดแต่งทรงได้',
  },
  {
    id: 'orchid', emoji: '🪻', nameTh: 'กล้วยไม้ (สกุลหวาย)', nameEn: 'Dendrobium orchid', scientificName: 'Dendrobium spp.',
    category: 'กล้วยไม้', difficulty: 'ปานกลาง', suitableForPot: true, suitableForGround: false,
    medium: 'orchid',
    sunlight: { minHours: 3, label: 'แสงรำไร', text: 'ชอบแดดเช้าหรือแสงรำไร (ใต้ซาแรน/ใต้ต้นไม้) ไม่โดนแดดเที่ยงตรงจัด' },
    waterNeed: 'medium',
    wateringGuideline: 'รดช่วงเช้าให้วัสดุปลูกชุ่ม แล้วปล่อยให้แห้งหมาด ๆ ก่อนรดครั้งต่อไป รากเน่าถ้าชื้นแฉะตลอด',
    soilGuideline: 'ไม่ปลูกในดิน ใช้กาบมะพร้าว ถ่าน หรือวัสดุโปร่งสำหรับกล้วยไม้',
    fertilizerGuideline: 'ใช้ปุ๋ยสำหรับกล้วยไม้ ผสมน้ำตามอัตราบนฉลาก ห้ามเข้มข้นกว่าที่ฉลากกำหนด',
    fertStartDay: 14, fertIntervalDays: 7,
    temperatureNotes: 'ชอบอากาศถ่ายเท ความชื้นสูง',
    floweringStartDay: 120,
    floweringNotes: 'ออกดอกเมื่อต้นสมบูรณ์ ระยะเวลาขึ้นกับอายุต้นที่ซื้อมา ไม่สามารถกำหนดวันแน่นอนได้',
    pruningNotes: 'ตัดช่อดอกที่โรยหมดแล้วออก',
    pruneTasks: [],
    pestNotes: 'เพลี้ยไฟ ไรแดง หอยทาก',
    diseaseNotes: 'รากเน่า โคนเน่าเมื่อชื้นแฉะ ใบจุดช่วงฝนชุก',
    commonProblems: ['รากเน่าจากความชื้นสูงตลอด', 'ใบไหม้เมื่อโดนแดดจัด'],
    image: { kind: 'orchid', petal: '#B66AD6', center: '#F7D24A', bg: '#F0E4F7' },
    description: 'ดอกสวยทน ต้องใช้วัสดุปลูกเฉพาะ แต่ดูแลไม่ยากถ้ารู้หลัก',
  },
  {
    id: 'anthurium', emoji: '❤️', nameTh: 'หน้าวัว', nameEn: 'Anthurium', scientificName: 'Anthurium andraeanum',
    category: 'ไม้ดอกในร่ม', difficulty: 'ปานกลาง', suitableForPot: true, suitableForGround: false,
    medium: 'airy',
    sunlight: { minHours: 2, label: 'แสงรำไร/ในร่ม', text: 'ชอบแสงสว่างแต่ไม่โดนแดดตรง ใต้ชายคาหรือใต้ซาแรนกำลังดี' },
    waterNeed: 'medium',
    wateringGuideline: 'ให้วัสดุปลูกชื้นหมาด ๆ ไม่แฉะ ชอบความชื้นในอากาศ',
    soilGuideline: 'วัสดุปลูกโปร่ง เช่น กาบมะพร้าวสับผสมถ่าน ระบายน้ำดีมาก',
    fertilizerGuideline: 'ใช้ปุ๋ยตามอัตราบนฉลาก แบบเจือจางตามคำแนะนำ',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'แดดจัดและลมร้อนทำให้ใบไหม้',
    floweringStartDay: 90,
    floweringNotes: 'ส่วนที่เป็นสีแดงมันคือใบประดับ อยู่ได้นานหลายสัปดาห์',
    pruningNotes: 'ตัดใบแก่ที่เหลืองและก้านดอกที่โรย',
    pruneTasks: [],
    pestNotes: 'เพลี้ยไฟ เพลี้ยแป้ง',
    diseaseNotes: 'ใบไหม้ขอบเมื่อแดดจัด รากเน่าเมื่อแฉะ',
    commonProblems: ['ใบไหม้เมื่อโดนแดดจัด', 'รากเน่า'],
    image: { kind: 'anthurium', petal: '#D7263D', center: '#F5D76E', bg: '#FCE1E4' },
    description: 'ใบประดับสีแดงมัน เหมาะกับมุมแสงรำไร',
  },
  {
    id: 'begonia', emoji: '🌷', nameTh: 'บีโกเนีย', nameEn: 'Begonia', scientificName: 'Begonia spp.',
    category: 'ไม้ดอกแสงรำไร', difficulty: 'ปานกลาง', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 2, label: 'แดดเช้า/แสงรำไร', text: 'ชอบแดดเช้าอ่อน ๆ หรือแสงรำไร แดดบ่ายจัดทำให้ใบไหม้' },
    waterNeed: 'medium',
    wateringGuideline: 'รดเมื่อผิวดินเริ่มแห้ง รดที่โคน ไม่รดโดนใบ ไม่ชอบน้ำขัง',
    soilGuideline: 'ดินร่วนโปร่ง ระบายน้ำดี',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลาก แบบเจือจางตามคำแนะนำ',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'ไม่ชอบร้อนจัดและแดดแรง เหมาะวางใต้ชายคา',
    floweringStartDay: 60,
    floweringNotes: 'ออกดอกเป็นช่อเล็ก ๆ ต่อเนื่องเมื่อได้แสงพอดี',
    pruningNotes: 'เด็ดดอกโรยและใบเสียออก',
    pruneTasks: [],
    deadhead: true,
    pestNotes: 'เพลี้ยแป้ง หอยทาก',
    diseaseNotes: 'ราแป้ง ลำต้นเน่าเมื่อแฉะ',
    commonProblems: ['ลำต้นเน่าจากน้ำขัง', 'ใบไหม้แดด'],
    image: { kind: 'begonia', petal: '#F58FA6', center: '#F7D24A', bg: '#FDE6EC' },
    description: 'ดอกและใบสวย เหมาะกับมุมที่แดดไม่จัด',
  },
  /* ---- เพิ่มชุดที่ 2: ไม้ดอกตระกูลเดซี่ (ใช้ schema เดิม + ฟิลด์เสริมทั่วไปที่ไม่บังคับ) ---- */
  {
    id: 'marguerite', emoji: '🌼', nameTh: 'มากาเร็ต', nameEn: 'Marguerite Daisy', scientificName: 'Argyranthemum frutescens',
    category: 'ไม้ดอก', difficulty: 'ง่าย–ปานกลาง', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 4, label: 'แดด 4–6 ชั่วโมง', text: 'ควรได้แดดประมาณ 4–6 ชั่วโมงต่อวัน แดดเช้าดีที่สุด ในพื้นที่ร้อนอย่างภาคกลาง ถ้ามีร่มเงาช่วงบ่ายจะช่วยให้ต้นไม่โทรมเร็ว' },
    waterNeed: 'medium',
    wateringGuideline: 'ตรวจดินก่อนรดทุกครั้ง รดเมื่อหน้าดินลึก 2–3 ซม. เริ่มแห้ง หลีกเลี่ยงน้ำขังในจานรองหรือรอบโคน',
    soilGuideline: 'ดินโปร่ง ระบายน้ำดี ถ้าปลูกกระถางใช้ดินผสมพร้อมปลูกที่ร่วนซุย ถ้าลงดินควรผสมปุ๋ยหมักให้ดินร่วน',
    fertilizerGuideline: 'หลังต้นตั้งตัวประมาณ 3 สัปดาห์ ใส่ปุ๋ยตามอัตราบนฉลากผลิตภัณฑ์ ช่วงอากาศร้อนจัดที่ต้นดูโทรม ไม่ควรเร่งใส่ปุ๋ยเพิ่ม',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'อากาศร้อนจัดอาจทำให้ต้นโทรมและออกดอกลดลง ช่วงบ่ายที่ร้อนมาก ลองย้ายกระถางไปที่มีร่มรำไร',
    floweringStartDay: 60,
    floweringNotes: 'ออกดอกได้ดีในช่วงอากาศไม่ร้อนจัด ช่วงหน้าร้อนอาจมีดอกน้อยลง เป็นเรื่องที่เกิดได้ ระยะเวลาขึ้นกับพันธุ์และสภาพแวดล้อม',
    pruningNotes: 'เด็ดยอดช่วงแรกเพื่อให้แตกพุ่ม เด็ดดอกที่โรยออก และตัดแต่งกิ่งที่ยืดยาวเบา ๆ เมื่อต้นเริ่มเสียทรง',
    pruneTasks: [{ day: 21, title: 'เด็ดยอดให้แตกพุ่ม' }, { day: 60, every: 30, title: 'ตัดแต่งกิ่งที่ยืดยาวเบา ๆ' }],
    deadhead: true,
    careNotes: 'หัวใจของมากาเร็ตคือ "แตกพุ่ม" ยิ่งมีกิ่งมาก ยิ่งมีที่ให้ดอกออก เด็ดยอดและเด็ดดอกโรยอย่างสม่ำเสมอ และระวังดินแฉะ',
    extraChecks: [
      { key: 'bush', type: 'GENERAL', startDay: 10, every: 7, title: 'ตรวจการแตกพุ่ม ({name})', description: 'ดูว่าต้นแตกกิ่งข้างรอบต้น หรือยืดสูงไปทางเดียว',
        steps: ['ดูว่ามีกิ่งข้างแตกออกมาใหม่ไหม', 'ถ้าต้นยืดสูงโปร่ง ลองเด็ดปลายยอดออกเล็กน้อย', 'ถ้าเอนไปทางเดียว ลองหมุนกระถางให้ได้แดดทั่วต้น'] },
    ],
    pestNotes: 'เพลี้ยอ่อน เพลี้ยไฟ และหนอนกินใบ ตรวจใต้ใบและยอดอ่อนเป็นประจำ',
    diseaseNotes: 'รากและโคนเสียหายเมื่อดินแฉะนาน ใบเหี่ยวทั้งที่ดินชื้นเป็นสัญญาณที่ควรตรวจราก',
    commonProblems: ['ใบเหี่ยวช่วงร้อนจัด', 'ดินแฉะ/รากมีปัญหา', 'เพลี้ยตามยอดอ่อน', 'ออกดอกน้อยช่วงหน้าร้อน'],
    doctorHints: [
      { symptoms: ['wilt'], when: { wiltTime: ['afternoon'] }, title: 'มีความเป็นไปได้ว่ามากาเร็ตกำลังเครียดจากความร้อน', why: 'มากาเร็ตไม่ชอบอากาศร้อนจัด ช่วงบ่ายจึงเหี่ยวได้ง่าย ถ้าฟื้นตอนเย็นมักไม่อันตราย',
        checks: ['ดูว่าเหี่ยวเฉพาะช่วงบ่ายแล้วฟื้นตอนเย็นหรือไม่'], actions: ['ถ้าปลูกกระถาง ย้ายไปที่มีร่มรำไรช่วงบ่าย', 'ตรวจดินตอนเช้า ถ้าดินชื้นอยู่ยังไม่ต้องรดเพิ่ม'] },
      { symptoms: ['wilt', 'yellow', 'soggy'], when: { soil: ['wet'] }, title: 'อาจเกิดจากดินแฉะจนรากมีปัญหา', why: 'มากาเร็ตไม่ชอบน้ำขัง รากที่แช่น้ำนานจะดูดน้ำไม่ได้ ต้นจึงเหี่ยวทั้งที่ดินชื้น',
        checks: ['ดูว่ามีน้ำขังในจานรองหรือรอบโคนไหม', 'ดูโคนต้นว่านิ่มหรือเปลี่ยนสีไหม'], actions: ['งดรดน้ำจนหน้าดินเริ่มแห้ง', 'เทน้ำในจานรองทิ้ง'] },
      { symptoms: ['noflower'], title: 'อาจเกี่ยวกับอากาศร้อนจัดหรือต้นยังไม่แตกพุ่มพอ', why: 'มากาเร็ตมักออกดอกน้อยลงช่วงอากาศร้อนจัด และต้นที่มีกิ่งน้อยก็จะมีจุดให้ดอกออกน้อย',
        checks: ['ดูว่าต้นมีกิ่งแตกพุ่มหรือยืดเป็นกิ่งเดียว'], actions: ['เด็ดยอดและเด็ดดอกโรยเพื่อกระตุ้นการแตกกิ่งใหม่', 'ให้แดดเช้าเต็มที่ แต่มีร่มช่วงบ่าย'] },
      { symptoms: ['nogrowth'], title: 'มีความเป็นไปได้ว่าต้นยืดแต่ไม่แตกพุ่ม', why: 'ถ้าไม่เด็ดยอด มากาเร็ตอาจโตขึ้นเป็นกิ่งยาวโปร่ง',
        checks: ['ดูจำนวนกิ่งข้าง'], actions: ['เด็ดปลายยอดออกประมาณ 1–2 ซม. เหนือข้อใบ'] },
    ],
    image: { kind: 'daisy', petal: '#FFFFFF', center: '#F2B705', bg: '#FFF6D6', stroke: '#EADFC0', src: null },
    description: 'ดอกขาวใจเหลืองน่ารัก ออกดอกดกเมื่อแตกพุ่มดี เหมาะกับมุมที่ได้แดดเช้าและมีร่มบ่าย',
  },
  {
    id: 'daisy', emoji: '🌼', nameTh: 'เดซี่', nameEn: 'Daisy', scientificName: '',
    category: 'ไม้ดอก', difficulty: 'ปานกลาง', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 4, label: 'แดด 4–6 ชั่วโมง', text: 'ควรได้แดดประมาณ 4–6 ชั่วโมงต่อวัน และวางในที่ลมพัดผ่าน ในอากาศร้อนควรเลี่ยงแดดบ่ายจัด' },
    waterNeed: 'medium',
    wateringGuideline: 'ตรวจดินก่อนรด รดเมื่อดินเริ่มแห้ง ไม่ควรปล่อยให้แฉะ รดที่โคนต้นและเลี่ยงการรดโดนดอก',
    soilGuideline: 'ดินโปร่ง ระบายน้ำดี ปลูกในกระถางหรือแปลงที่น้ำไม่ขัง',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลากผลิตภัณฑ์หลังต้นตั้งตัว ไม่ใส่เกินฉลากเพื่อเร่งดอก',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'อากาศเย็นเหมาะกับการออกดอกมากกว่าอากาศร้อนจัด ในภาคกลางช่วงปลายฝนถึงหน้าหนาวมักดูแลง่ายกว่าหน้าร้อน',
    floweringStartDay: 60,
    floweringNotes: 'การออกดอกขึ้นกับแสงที่เพียงพอและอากาศถ่ายเท เดซี่มีหลายพันธุ์ ระยะเวลาออกดอกจึงต่างกันไป ไม่มีวันที่แน่นอน',
    pruningNotes: 'เด็ดดอกโรยออกสม่ำเสมอเพื่อช่วยกระตุ้นให้ออกดอกใหม่ และตัดใบแห้งใบเสียออก',
    pruneTasks: [],
    deadhead: true,
    careNotes: 'ให้ความสำคัญกับ 2 เรื่อง: แสงเพียงพอ และอากาศถ่ายเท อย่าวางกระถางชิดกันแน่น เด็ดดอกโรยเป็นประจำ',
    pestNotes: 'เพลี้ยอ่อน เพลี้ยไฟ และไรแดงช่วงอากาศร้อนแห้ง',
    diseaseNotes: 'ใบไหม้เมื่อโดนแดดบ่ายจัด รากเสียหายเมื่อดินแฉะนาน ราแป้งเมื่ออากาศชื้นและลมไม่ถ่ายเท',
    commonProblems: ['ต้นเหี่ยวช่วงร้อน', 'ใบไหม้จากแดดจัด', 'ดินแฉะ', 'เพลี้ยและไรแดง', 'ออกดอกน้อย'],
    doctorHints: [
      { symptoms: ['noflower'], title: 'อาจเกี่ยวกับอากาศร้อนจัด แสงไม่พอ หรืออากาศไม่ถ่ายเท', why: 'เดซี่มักออกดอกได้ดีกว่าในช่วงอากาศเย็น และต้องการแสงเพียงพอร่วมกับลมที่พัดผ่าน',
        checks: ['ดูว่าที่วางได้แดดประมาณ 4–6 ชั่วโมงไหม', 'ดูว่ากระถางวางชิดกันจนลมไม่ผ่านหรือไม่'], actions: ['เด็ดดอกโรยออก', 'ย้ายไปที่ได้แดดเช้าเต็มที่และลมผ่าน'] },
      { symptoms: ['burn'], when: { sun: ['5to7', 'gt7'] }, title: 'มีความเป็นไปได้ว่าโดนแดดบ่ายร้อนจัดเกินไป', why: 'เดซี่ไม่ชอบความร้อนจัด แดดบ่ายในภาคกลางอาจทำให้ใบไหม้',
        checks: ['ดูว่าใบที่ไหม้อยู่ด้านที่หันรับแดดบ่ายไหม'], actions: ['ให้ร่มรำไรช่วงบ่าย', 'ตรวจดินตอนเช้าอย่าปล่อยให้แห้งจัด'] },
      { symptoms: ['wilt', 'soggy', 'yellow'], when: { soil: ['wet'] }, title: 'อาจเกิดจากดินแฉะหรือระบายน้ำไม่ดี', why: 'เดซี่ไม่ควรปล่อยให้ดินแฉะ รากที่ชื้นตลอดจะเสียหายได้',
        checks: ['ดูว่ามีน้ำขังก้นกระถางหรือในแปลงไหม'], actions: ['งดรดน้ำจนดินเริ่มแห้ง', 'ตรวจว่ารูระบายน้ำไม่ตัน'] },
      { symptoms: ['spots'], when: { spotType: ['white'] }, title: 'ควรตรวจเรื่องอากาศถ่ายเท', why: 'ผงขาวบนใบของเดซี่มักพบเมื่ออากาศชื้นและลมไม่ผ่าน',
        checks: ['ดูระยะห่างระหว่างกระถาง'], actions: ['จัดกระถางให้ห่างกันขึ้น', 'รดน้ำที่โคน ไม่รดโดนใบ'] },
    ],
    image: { kind: 'daisy', petal: '#F7C6D9', center: '#F2B705', bg: '#FDE8F0', layers: 2, src: null },
    description: 'ดอกเล็กสดใส มีหลายพันธุ์ ออกดอกได้ดีในช่วงอากาศเย็น ต้องการแสงพอและลมผ่าน',
  },
  {
    id: 'gerbera', emoji: '🌸', nameTh: 'เยอบีร่า', nameEn: 'Gerbera Daisy', scientificName: 'Gerbera jamesonii',
    category: 'ไม้ดอก', difficulty: 'ปานกลาง–ค่อนข้างยาก', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 4, label: 'แดด 4–6 ชั่วโมง (เน้นแดดเช้า)', text: 'ควรได้แดดประมาณ 4–6 ชั่วโมงต่อวัน โดยเฉพาะแดดช่วงเช้า ถ้าแดดบ่ายร้อนจัด ควรพิจารณาพรางแสงช่วงบ่าย' },
    waterNeed: 'medium',
    wateringGuideline: 'ตรวจดินก่อนรดทุกครั้ง รดเมื่อดินเริ่มแห้ง รดที่ดินรอบ ๆ ต้น ไม่รดลงกลางกอหรือให้น้ำค้างที่โคน และหลีกเลี่ยงน้ำขังเด็ดขาด',
    soilGuideline: 'ดินหรือวัสดุปลูกที่โปร่งมาก ระบายน้ำดี ถ้าปลูกลงแปลง ควรยกแปลงให้น้ำไม่ขัง',
    fertilizerGuideline: 'ใส่ปุ๋ยตามอัตราบนฉลากผลิตภัณฑ์หลังต้นตั้งตัว ไม่โรยปุ๋ยกองชิดโคนต้น',
    fertStartDay: 21, fertIntervalDays: 30,
    temperatureNotes: 'แดดบ่ายในภาคกลางร้อนจัด อาจทำให้ใบไหม้หรือต้นเหี่ยว ควรมีร่มรำไรช่วงบ่าย',
    floweringStartDay: 75,
    floweringNotes: 'ต้องการแสงเพียงพอและสภาพแวดล้อมที่ไม่แฉะ ดอกอาจออกเป็นช่วง ๆ ระยะเวลาขึ้นกับพันธุ์และอายุต้น ไม่มีวันที่แน่นอน',
    pruningNotes: 'ตัดก้านดอกที่โรยออกที่โคนก้าน และเด็ดใบแก่ที่เหลืองหรือเสียบริเวณโคนออก ให้โคนโปร่ง',
    pruneTasks: [],
    deadhead: true,
    careNotes: 'เยอบีร่าเสียหายง่ายที่สุดจาก "โคนต้นเปียกแฉะ" ให้โคนโปร่ง แห้ง ไม่ถูกดินกลบ และตรวจน้ำขังเป็นประจำ',
    warnings: [
      'ระวังน้ำขัง: เยอบีร่าเสี่ยงรากเน่าและโคนเน่า ตรวจดินก่อนรดทุกครั้ง และเทน้ำในจานรองทิ้งเสมอ',
      'อย่าปลูกลึกจนดินกลบคอ/โคนต้น ให้ส่วนโคนที่ใบแตกออกอยู่เหนือผิวดินเล็กน้อย',
    ],
    plantingSteps: ['เตรียมกระถางที่มีรูระบายน้ำ หรือแปลงที่ยกสูง', 'ใส่ดิน/วัสดุปลูกที่โปร่งมาก ระบายน้ำดี', 'ค่อย ๆ ถอดต้นออกจากถุง ระวังรากแตก', 'วางต้นให้โคน (จุดที่ใบแตกออก) อยู่เหนือผิวดินเล็กน้อย ห้ามกลบลึก', 'กลบดินรอบ ๆ และกดเบา ๆ โดยไม่กลบโคน', 'รดน้ำที่ดินรอบต้นให้ชุ่ม ไม่รดลงกลางกอ'],
    extraChecks: [
      { key: 'crown', type: 'DISEASE_CHECK', startDay: 1, every: 3, title: 'ตรวจบริเวณโคนต้น ({name})', description: 'โคนต้นคือจุดที่เยอบีร่าเสียหายง่ายที่สุด',
        steps: ['ดูว่าโคนต้นไม่ถูกดินกลบ', 'ดูว่าโคนแห้ง ไม่นิ่มหรือเปลี่ยนสีเข้ม', 'เด็ดใบแก่ที่เหลืองหรือเน่าบริเวณโคนออก'] },
      { key: 'waterlog', type: 'GENERAL', startDay: 2, every: 4, title: 'ตรวจน้ำขัง ({name})', description: 'น้ำขังทำให้รากและโคนเน่าได้',
        steps: ['ดูจานรองกระถางว่ามีน้ำค้างไหม ถ้ามี เททิ้ง', 'ถ้าปลูกลงแปลง ดูว่ามีน้ำขังรอบต้นหลังรดน้ำหรือฝนตกไหม', 'ถ้าน้ำขังบ่อย พิจารณายกกระถางหรือยกแปลงให้สูงขึ้น'] },
    ],
    pestNotes: 'เพลี้ยไฟ เพลี้ยอ่อน แมลงหวี่ขาว และไรแดง ตรวจใต้ใบและดอกตูม',
    diseaseNotes: 'รากเน่า/โคนเน่าเมื่อดินแฉะหรือโคนถูกกลบลึก ใบไหม้เมื่อโดนแดดบ่ายจัด ใบจุดเมื่อใบเปียกนาน',
    commonProblems: ['โคนเน่า/รากมีปัญหาจากน้ำขัง', 'ใบเหี่ยว', 'ใบไหม้จากแดดบ่าย', 'เพลี้ยไฟและไรแดง', 'ไม่ออกดอก'],
    doctorHints: [
      { symptoms: ['wilt', 'yellow', 'soggy'], when: { soil: ['wet', 'moist'] }, title: 'อาจเกี่ยวข้องกับความชื้นในดินมากเกินไปหรือการระบายน้ำไม่ดี', why: 'เยอบีร่าไวต่อน้ำขังเป็นพิเศษ ถ้าดินชื้นแฉะต่อเนื่อง มีความเป็นไปได้ว่ารากหรือโคนต้นเริ่มเสียหาย',
        checks: ['ตรวจว่ามีน้ำขังบริเวณโคนต้นหรือในจานรองหรือไม่', 'ดูว่าโคนต้นนิ่ม ดำ หรือถูกดินกลบลึกเกินไปหรือไม่'],
        actions: ['งดรดน้ำจนกว่าดินจะเริ่มแห้ง', 'เขี่ยดินที่กลบโคนออก ให้โคนต้นอยู่เหนือผิวดินเล็กน้อย', 'ถ้าดินแน่นมาก พิจารณาย้ายไปปลูกในวัสดุที่โปร่งกว่า'] },
      { symptoms: ['burn', 'wilt'], when: { sun: ['5to7', 'gt7'] }, title: 'มีความเป็นไปได้ว่าโดนแดดบ่ายร้อนจัด', why: 'เยอบีร่าชอบแดดเช้า แดดบ่ายในภาคกลางอาจทำให้ใบไหม้หรือเหี่ยว',
        checks: ['ดูว่าตำแหน่งปลูกโดนแดดตรงช่วงบ่ายไหม'], actions: ['พรางแสงช่วงบ่าย เช่น ย้ายกระถางใต้ชายคาหรือใช้ซาแรน'] },
      { symptoms: ['noflower'], title: 'ควรตรวจเรื่องแสงและความแฉะของดิน', why: 'เยอบีร่าต้องการแสงเพียงพอ (โดยเฉพาะแดดเช้า) และสภาพแวดล้อมที่ไม่แฉะจึงจะออกดอกได้ดี',
        checks: ['ดูว่าได้แดดเช้าเพียงพอหรือไม่', 'ดูว่าดินแฉะบ่อยหรือไม่'], actions: ['ตัดก้านดอกโรยที่โคนก้าน', 'เด็ดใบแก่บริเวณโคนออกให้โคนโปร่ง'] },
      { symptoms: ['spots'], title: 'ควรตรวจว่าใบและโคนเปียกน้ำนานหรือไม่', why: 'ใบที่เปียกนานหรือโคนที่ชื้นตลอดเพิ่มโอกาสเกิดจุดบนใบ',
        checks: ['ดูว่ารดน้ำโดนใบหรือกลางกอบ่อยไหม'], actions: ['รดที่ดินรอบต้นช่วงเช้า ไม่รดลงกลางกอ', 'เด็ดใบที่มีจุดออก'] },
    ],
    image: { kind: 'daisy', petal: '#F46A3B', center: '#5A3A1E', bg: '#FFE6DA', big: true, src: null },
    description: 'ดอกใหญ่สีสด สวยมาก แต่ต้องใส่ใจเรื่องน้ำขังและโคนต้นเป็นพิเศษ เหมาะกับคนที่เริ่มคล่องขึ้นแล้ว',
  },
];

/** ค่าเริ่มต้นสำหรับ "ต้นไม้ชนิดอื่น" ที่ผู้ใช้เพิ่มเอง */
function makeCustomSpecies(nameTh) {
  return {
    id: 'custom_' + Date.now().toString(36), custom: true, emoji: '🪴', nameTh, nameEn: '', scientificName: '',
    category: 'ต้นไม้ที่เพิ่มเอง', difficulty: '-', suitableForPot: true, suitableForGround: true,
    sunlight: { minHours: 0, label: 'ยังไม่มีข้อมูล', text: 'ลองถามร้านต้นไม้ว่าต้นนี้ชอบแดดจัดหรือแสงรำไร แล้วจดไว้ในหมายเหตุ' },
    waterNeed: 'medium',
    wateringGuideline: 'ใช้หลักทั่วไป: ตรวจดินก่อนรด ถ้าดินลึก 2–3 ซม. แห้ง ค่อยรดน้ำ',
    soilGuideline: 'ดินร่วนผสมปุ๋ยหมัก ระบายน้ำดี',
    fertilizerGuideline: 'ใช้ตามอัตราบนฉลากผลิตภัณฑ์',
    fertStartDay: 30, fertIntervalDays: 30,
    temperatureNotes: '', floweringStartDay: 90,
    floweringNotes: 'ระยะออกดอกขึ้นกับชนิดและพันธุ์',
    pruningNotes: 'ตัดใบหรือกิ่งที่แห้ง เสีย ออก', pruneTasks: [],
    pestNotes: 'ตรวจใต้ใบและยอดอ่อนเป็นประจำ', diseaseNotes: '',
    commonProblems: [],
    image: { kind: 'sprout', petal: '#7CC59A', center: '#4E9A6E', bg: '#E3F4E9' },
    description: 'ต้นไม้ที่คุณเพิ่มเอง ระบบจะใช้คำแนะนำทั่วไปที่ปลอดภัย',
  };
}
